%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_rpc_compile
-module(msg_base).

-callback heartbeat(msg_base_pb:HeartbeatReq(), ex_msg:state()) -> ex_msg:resp_maps().
