%% -*- coding: utf-8 -*-
%% @private
%% Automatically @generated, do not edit
%% Generated by gpb_compile version 4.21.5
%% Version source: file
-module(msg_base_pb).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([enum_symbol_by_value_c_cmd/1, enum_value_by_symbol_c_cmd/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("msg_base_pb.hrl").
-include("gpb.hrl").

%% enumerated types
-type c_cmd() :: 'HeartbeatReq' | 'HeartbeatResp'.
-export_type([c_cmd/0]).

%% message types
-type 'HeartbeatReq'() :: #'HeartbeatReq'{}.

-type 'HeartbeatResp'() :: #'HeartbeatResp'{}.

-type 'Empty'() :: #'Empty'{}.

-export_type(['HeartbeatReq'/0, 'HeartbeatResp'/0, 'Empty'/0]).
-type '$msg_name'() :: 'HeartbeatReq' | 'HeartbeatResp' | 'Empty'.
-type '$msg'() :: 'HeartbeatReq'() | 'HeartbeatResp'() | 'Empty'().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/1}).
-endif.
-spec encode_msg('$msg'()) -> <<>>.
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> <<>>.
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> <<>>.
encode_msg(Msg, MsgName, Opts) ->
    verify_msg(Msg, MsgName, Opts),
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'HeartbeatReq' -> encode_msg_HeartbeatReq(id(Msg, TrUserData), TrUserData);
        'HeartbeatResp' -> encode_msg_HeartbeatResp(id(Msg, TrUserData), TrUserData);
        'Empty' -> encode_msg_Empty(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_HeartbeatReq(_Msg, _TrUserData) -> <<>>.

encode_msg_HeartbeatResp(_Msg, _TrUserData) -> <<>>.

encode_msg_Empty(_Msg, _TrUserData) -> <<>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('HeartbeatReq', Bin, TrUserData) -> id(decode_msg_HeartbeatReq(Bin, TrUserData), TrUserData);
decode_msg_2_doit('HeartbeatResp', Bin, TrUserData) -> id(decode_msg_HeartbeatResp(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Empty', Bin, TrUserData) -> id(decode_msg_Empty(Bin, TrUserData), TrUserData).



decode_msg_HeartbeatReq(Bin, TrUserData) -> dfp_read_field_def_HeartbeatReq(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_HeartbeatReq(<<>>, 0, 0, _, _) -> #'HeartbeatReq'{};
dfp_read_field_def_HeartbeatReq(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_HeartbeatReq(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_HeartbeatReq(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_HeartbeatReq(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_HeartbeatReq(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_HeartbeatReq(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_HeartbeatReq(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_HeartbeatReq(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_HeartbeatReq(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_HeartbeatReq(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_HeartbeatReq(<<>>, 0, 0, _, _) -> #'HeartbeatReq'{}.

skip_varint_HeartbeatReq(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_HeartbeatReq(Rest, Z1, Z2, F, TrUserData);
skip_varint_HeartbeatReq(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatReq(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_HeartbeatReq(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_HeartbeatReq(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_HeartbeatReq(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_HeartbeatReq(Rest2, 0, 0, F, TrUserData).

skip_group_HeartbeatReq(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_HeartbeatReq(Rest, 0, Z2, FNum, TrUserData).

skip_32_HeartbeatReq(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatReq(Rest, Z1, Z2, F, TrUserData).

skip_64_HeartbeatReq(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatReq(Rest, Z1, Z2, F, TrUserData).

decode_msg_HeartbeatResp(Bin, TrUserData) -> dfp_read_field_def_HeartbeatResp(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_HeartbeatResp(<<>>, 0, 0, _, _) -> #'HeartbeatResp'{};
dfp_read_field_def_HeartbeatResp(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_HeartbeatResp(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_HeartbeatResp(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_HeartbeatResp(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_HeartbeatResp(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_HeartbeatResp(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_HeartbeatResp(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_HeartbeatResp(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_HeartbeatResp(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_HeartbeatResp(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_HeartbeatResp(<<>>, 0, 0, _, _) -> #'HeartbeatResp'{}.

skip_varint_HeartbeatResp(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_HeartbeatResp(Rest, Z1, Z2, F, TrUserData);
skip_varint_HeartbeatResp(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatResp(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_HeartbeatResp(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_HeartbeatResp(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_HeartbeatResp(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_HeartbeatResp(Rest2, 0, 0, F, TrUserData).

skip_group_HeartbeatResp(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_HeartbeatResp(Rest, 0, Z2, FNum, TrUserData).

skip_32_HeartbeatResp(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatResp(Rest, Z1, Z2, F, TrUserData).

skip_64_HeartbeatResp(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_HeartbeatResp(Rest, Z1, Z2, F, TrUserData).

decode_msg_Empty(Bin, TrUserData) -> dfp_read_field_def_Empty(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_Empty(<<>>, 0, 0, _, _) -> #'Empty'{};
dfp_read_field_def_Empty(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_Empty(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_Empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_Empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_Empty(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_Empty(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_Empty(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_Empty(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_Empty(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_Empty(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_Empty(<<>>, 0, 0, _, _) -> #'Empty'{}.

skip_varint_Empty(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_Empty(Rest, Z1, Z2, F, TrUserData);
skip_varint_Empty(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_Empty(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_Empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_Empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_Empty(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Empty(Rest2, 0, 0, F, TrUserData).

skip_group_Empty(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Empty(Rest, 0, Z2, FNum, TrUserData).

skip_32_Empty(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_Empty(Rest, Z1, Z2, F, TrUserData).

skip_64_Empty(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_Empty(Rest, Z1, Z2, F, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'HeartbeatReq' -> merge_msg_HeartbeatReq(Prev, New, TrUserData);
        'HeartbeatResp' -> merge_msg_HeartbeatResp(Prev, New, TrUserData);
        'Empty' -> merge_msg_Empty(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_HeartbeatReq/3}).
merge_msg_HeartbeatReq(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_HeartbeatResp/3}).
merge_msg_HeartbeatResp(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_Empty/3}).
merge_msg_Empty(_Prev, New, _TrUserData) -> New.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'HeartbeatReq' -> v_msg_HeartbeatReq(Msg, [MsgName], TrUserData);
        'HeartbeatResp' -> v_msg_HeartbeatResp(Msg, [MsgName], TrUserData);
        'Empty' -> v_msg_Empty(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_HeartbeatReq/3}).
-dialyzer({nowarn_function,v_msg_HeartbeatReq/3}).
v_msg_HeartbeatReq(#'HeartbeatReq'{}, _Path, _) -> ok;
v_msg_HeartbeatReq(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'HeartbeatReq'}, X, Path).

-compile({nowarn_unused_function,v_msg_HeartbeatResp/3}).
-dialyzer({nowarn_function,v_msg_HeartbeatResp/3}).
v_msg_HeartbeatResp(#'HeartbeatResp'{}, _Path, _) -> ok;
v_msg_HeartbeatResp(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'HeartbeatResp'}, X, Path).

-compile({nowarn_unused_function,v_msg_Empty/3}).
-dialyzer({nowarn_function,v_msg_Empty/3}).
v_msg_Empty(#'Empty'{}, _Path, _) -> ok;
v_msg_Empty(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'Empty'}, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() -> [{{enum, c_cmd}, [{'HeartbeatReq', 0}, {'HeartbeatResp', 1}]}, {{msg, 'HeartbeatReq'}, []}, {{msg, 'HeartbeatResp'}, []}, {{msg, 'Empty'}, []}].


get_msg_names() -> ['HeartbeatReq', 'HeartbeatResp', 'Empty'].


get_group_names() -> [].


get_msg_or_group_names() -> ['HeartbeatReq', 'HeartbeatResp', 'Empty'].


get_enum_names() -> [c_cmd].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
        Es when is_list(Es) -> Es;
        error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def('HeartbeatReq') -> [];
find_msg_def('HeartbeatResp') -> [];
find_msg_def('Empty') -> [];
find_msg_def(_) -> error.


find_enum_def(c_cmd) -> [{'HeartbeatReq', 0}, {'HeartbeatResp', 1}];
find_enum_def(_) -> error.


enum_symbol_by_value(c_cmd, Value) -> enum_symbol_by_value_c_cmd(Value).


enum_value_by_symbol(c_cmd, Sym) -> enum_value_by_symbol_c_cmd(Sym).


enum_symbol_by_value_c_cmd(0) -> 'HeartbeatReq';
enum_symbol_by_value_c_cmd(1) -> 'HeartbeatResp'.


enum_value_by_symbol_c_cmd('HeartbeatReq') -> 0;
enum_value_by_symbol_c_cmd('HeartbeatResp') -> 1.


get_service_names() -> [msg_base_service].


get_service_def(msg_base_service) -> {{service, msg_base_service}, [#rpc{name = heartbeat, input = 'HeartbeatReq', output = 'HeartbeatResp', input_stream = false, output_stream = false, opts = []}]};
get_service_def(_) -> error.


get_rpc_names(msg_base_service) -> [heartbeat];
get_rpc_names(_) -> error.


find_rpc_def(msg_base_service, RpcName) -> find_rpc_def_msg_base_service(RpcName);
find_rpc_def(_, _) -> error.


find_rpc_def_msg_base_service(heartbeat) -> #rpc{name = heartbeat, input = 'HeartbeatReq', output = 'HeartbeatResp', input_stream = false, output_stream = false, opts = []};
find_rpc_def_msg_base_service(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_tuple(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"google.protobuf.msg_base_service">>) -> msg_base_service;
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin(msg_base_service) -> <<"google.protobuf.msg_base_service">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"google.protobuf.msg_base_service">>, <<"heartbeat">>) -> {msg_base_service, heartbeat};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins(msg_base_service, heartbeat) -> {<<"google.protobuf.msg_base_service">>, <<"heartbeat">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"google.protobuf.HeartbeatReq">>) -> 'HeartbeatReq';
fqbin_to_msg_name(<<"google.protobuf.HeartbeatResp">>) -> 'HeartbeatResp';
fqbin_to_msg_name(<<"google.protobuf.Empty">>) -> 'Empty';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('HeartbeatReq') -> <<"google.protobuf.HeartbeatReq">>;
msg_name_to_fqbin('HeartbeatResp') -> <<"google.protobuf.HeartbeatResp">>;
msg_name_to_fqbin('Empty') -> <<"google.protobuf.Empty">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"google.protobuf.c_cmd">>) -> c_cmd;
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin(c_cmd) -> <<"google.protobuf.c_cmd">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'google.protobuf'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "msg_base.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["msg_base.proto", "empty.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["msg_base", "empty"].


get_msg_containment("msg_base") -> ['HeartbeatReq', 'HeartbeatResp'];
get_msg_containment("empty") -> ['Empty'];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("msg_base") -> undefined;
get_pkg_containment("empty") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("msg_base") -> [msg_base_service];
get_service_containment("empty") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("msg_base") -> [{msg_base_service, heartbeat}];
get_rpc_containment("empty") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("msg_base") -> [c_cmd];
get_enum_containment("empty") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"google.protobuf.HeartbeatResp">>) -> "msg_base";
get_proto_by_msg_name_as_fqbin(<<"google.protobuf.HeartbeatReq">>) -> "msg_base";
get_proto_by_msg_name_as_fqbin(<<"google.protobuf.Empty">>) -> "empty";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"google.protobuf.msg_base_service">>) -> "msg_base";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"google.protobuf.c_cmd">>) -> "msg_base";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.21.5".

gpb_version_as_list() ->
    [4,21,5].

gpb_version_source() ->
    "file".
