%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(error_code).
-define(error_code, true).

-define(error_code_gpb_version, "4.21.5").



-endif.
