%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(error_code_pb).
-define(error_code_pb, true).

-define(error_code_pb_gpb_version, "4.21.5").



-endif.
