%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_rpc_compile
-ifndef(MSG_H).
-define(MSG_H, true).

%%%===================================================================
%%% cmd
%%%===================================================================
-define(CMD_MSG_BASE_HEARTBEATREQ, 0). % mod_cmd:0 ccmd:0
-define(CMD_MSG_BASE_HEARTBEATRESP, 1). % mod_cmd:0 ccmd:1
-define(CMD_MSG_USER_LOGINREQ, 512). % mod_cmd:1 ccmd:0
-define(CMD_MSG_USER_LOGINRESP, 513). % mod_cmd:1 ccmd:1

-ifdef(INCLUDE_ALL_PB_HRL).

-include("msg_base_pb.hrl").
-include("msg_user_pb.hrl").

-endif.

-endif.