%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_rpc_compile
-ifndef(MSG_USER_H).
-define(MSG_USER_H, true).

%% Code
-define(CODE_OK, 0). %% ok
-define(CODE_OK_KEY, 'ok'). %% 0
-define(CODE_FAIL, 1). %% fail
-define(CODE_FAIL_KEY, 'fail'). %% 1

-endif.
