%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(msg_user_pb).
-define(msg_user_pb, true).

-define(msg_user_pb_gpb_version, "4.21.5").


-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record('LoginReq',
        {account = <<>>         :: unicode:chardata() | undefined, % = 1, optional
         password = <<>>        :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('LOGINRESP_PB_H').
-define('LOGINRESP_PB_H', true).
-record('LoginResp',
        {code = ok              :: ok | fail | integer() | undefined, % = 1, optional, enum Code
         user_info = undefined  :: msg_user_pb:'UserInfo'() | undefined % = 2, optional
        }).
-endif.

-ifndef('USERINFO_PB_H').
-define('USERINFO_PB_H', true).
-record('UserInfo',
        {chips = 0              :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('EMPTY_PB_H').
-define('EMPTY_PB_H', true).
-record('Empty',
        {
        }).
-endif.

-endif.
