%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(msg_base_pb).
-define(msg_base_pb, true).

-define(msg_base_pb_gpb_version, "4.21.5").


-ifndef('HEARTBEATREQ_PB_H').
-define('HEARTBEATREQ_PB_H', true).
-record('HeartbeatReq',
        {
        }).
-endif.

-ifndef('HEARTBEATRESP_PB_H').
-define('HEARTBEATRESP_PB_H', true).
-record('HeartbeatResp',
        {
        }).
-endif.

-ifndef('EMPTY_PB_H').
-define('EMPTY_PB_H', true).
-record('Empty',
        {
        }).
-endif.

-endif.
