%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(msg_base_pb).
-define(msg_base_pb, true).

-define(msg_base_pb_gpb_version, "4.21.5").


-ifndef('HEART_BEAT_REQ_PB_H').
-define('HEART_BEAT_REQ_PB_H', true).
-record(heart_beat_req,
        {
        }).
-endif.

-ifndef('HEART_BEAT_RESP_PB_H').
-define('HEART_BEAT_RESP_PB_H', true).
-record(heart_beat_resp,
        {
        }).
-endif.

-ifndef('EMPTY_PB_H').
-define('EMPTY_PB_H', true).
-record(empty,
        {
        }).
-endif.

-endif.
