%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(user).
-define(user, true).

-define(user_gpb_version, "4.21.5").


-ifndef('LOGINREQUEST_PB_H').
-define('LOGINREQUEST_PB_H', true).
-record('LoginRequest',
        {account = []           :: unicode:chardata() | undefined, % = 1, optional
         password = []          :: unicode:chardata() | undefined, % = 2, optional
         game_id = 0            :: non_neg_integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-ifndef('LOGINREPLY_PB_H').
-define('LOGINREPLY_PB_H', true).
-record('LoginReply',
        {code = ok              :: ok | fail | integer() | undefined, % = 1, optional, enum Code
         token = []             :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('USERINFO_PB_H').
-define('USERINFO_PB_H', true).
-record('UserInfo',
        {account = []           :: unicode:chardata() | undefined, % = 1, optional
         game_id = 0            :: non_neg_integer() | undefined, % = 2, optional, 32 bits
         chips = 0              :: non_neg_integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-endif.
